version: "3.8"
services:
  db:
    # build: ./docker/db
    container_name: ytb_mysql
    image: mysql:8.0
    ports:
      # - 3306:3306
      - "127.0.0.1:3306:3306"
    environment:
      - MYSQL_USER=claudiu
      - MYSQL_PASSWORD=claudiu
      - MYSQL_ROOT_PASSWORD=claudiu
      - MYSQL_DATABASE=projects
    volumes:
      - .docker/db/mysql-custom.cnf:/etc/mysql/conf.d/mysql-custom.cnf
      - ./sql/tables:/docker-entrypoint-initdb.d
  web:
    container_name: ytb_web
    build: ./docker/php
    ports:
      - 80:80
    volumes:
    - ./web:/var/www/html
  # python:
  #   build: ./docker/python